local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

LSM:Register("statusbar","ElvUI Gloss", [[Interface\AddOns\ElvUI\media\textures\normTex.tga]])
LSM:Register("statusbar","ElvUI Norm", [[Interface\AddOns\ElvUI\media\textures\normTex2.tga]])
LSM:Register("background","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("border", "ElvUI GlowBorder", [[Interface\AddOns\ElvUI\media\textures\glowTex.tga]])
LSM:Register("font","ElvUI Font", [[Interface\AddOns\ElvUI\media\fonts\PT_Sans_Narrow.ttf]])
LSM:Register("font","NiteWolfUI Font", [[Interface\AddOns\ElvUI\media\fonts\expressway.ttf]])
LSM:Register("font","NiteWolfUI Alt Font", [[Interface\AddOns\ElvUI\media\fonts\acmesa.TTF]])
LSM:Register("font","NiteWolfUI Pixel Font", [[Interface\AddOns\ElvUI\media\fonts\visitor1.ttf]])
LSM:Register("font","NiteWolfUI2 Pixel Font", [[Interface\AddOns\ElvUI\media\fonts\pf_tempesta_seven.ttf]])
LSM:Register("font","NiteWolfUI1 Combat", [[Interface\AddOns\ElvUI\media\fonts\Base_02.ttf]])
LSM:Register("font","NiteWolfUI2 Combat", [[Interface\AddOns\ElvUI\media\fonts\defused.ttf]])
LSM:Register("font","NiteWolfUI3 Combat", [[Interface\AddOns\ElvUI\media\fonts\ProjectY.ttf]])
LSM:Register("font","NiteWolfUI4 Combat", [[Interface\AddOns\ElvUI\media\fonts\SoulMission.ttf]])
LSM:Register("font","NiteWolfUI5 Combat", [[Interface\AddOns\ElvUI\media\fonts\Very_Damaged.ttf]])
LSM:Register("font","NiteWolfUI6 Combat", [[Interface\AddOns\ElvUI\media\fonts\28_days_later.ttf]])
LSM:Register("font", "ElvUI Alt-Font", [[Interface\AddOns\ElvUI\media\fonts\Continuum_Medium.ttf]])
LSM:Register("font", "ElvUI Pixel", [[Interface\AddOns\ElvUI\media\fonts\Homespun.ttf]])
LSM:Register("font","ElvUI Combat", [[Interface\AddOns\ElvUI\media\fonts\Action_Man.ttf]])
LSM:Register("font","ElvUI Alt-Combat", [[Interface\AddOns\ElvUI\media\fonts\DieDieDie.ttf]])
LSM:Register("sound","ElvUI Warning", [[Interface\AddOns\ElvUI\media\sounds\warning.mp3]])
LSM:Register("sound","ElvUI Whisper", [[Interface\AddOns\ElvUI\media\sounds\whisper.mp3]])